#cloud-config
autoinstall:
  # version is an Autoinstall required field.
  version: 1

  # This adds the default ubuntu-desktop packages to the system.
  # Any desired additional packages may also be listed here.
  packages:
    - ruby
    - ruby-dev
    - git
    - curl
    - build-essential
    - ssh
    - deja-dup

  # Any desired additional snaps may also be listed here.
  snaps:
    - name: warzone2100
    - name: spotify
    - name: kita
    - name: slack
    - name: openttd
    - name: bitwarden
    - name: bw
    - name: code
    
  # User creation can occur in one of 3 ways:
  # 1. Create a user using this `identity` section.
  # 2. Create users as documented in cloud-init inside the user-data section,
  #    which means this single-user identity section may be removed.
  # 3. Prompt for user configuration on first boot.  Remove this identity
  #    section and see the "Installation without a default user" section.
  identity:
    hostname: ubuntu-desktop-test

  # Subiquity will, by default, configure a partition layout using LVM.
  # The 'direct' layout method shown here will produce a non-LVM result.
  storage:
    layout:
      name: lvm
