#cloud-config
autoinstall:
  # version is an Autoinstall required field.
  version: 1

  # This adds the default ubuntu-desktop packages to the system.
  # Any desired additional packages may also be listed here.
  packages:
    - ruby
    - ruby-dev
    - git
    - curl
    - build-essential
    - ssh
    - deja-dup

  # Any desired additional snaps may also be listed here.
  snaps:
    - name: warzone2100
    - name: spotify
    - name: kita
    - name: slack
    - name: openttd
    - name: bitwarden
    - name: bw
    - name: code

  # Subiquity will, by default, configure a partition layout using LVM.
  # The 'direct' layout method shown here will produce a non-LVM result.
  storage:
    layout:
      name: lvm

  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *id001
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *id002
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: true
  drivers:
    install: false
  identity:
    hostname: dan-test
    password: $6$UM0qQAMwYUYCuPk2$.TH3kBSamBuuAYbaiIYvGkmb5dHgLPxcLvQDSz8Xhfi6ZF/u/CQUImFSVfARy56UJlKxjLnnyRz0ahRu./mPe/
    realname: Dan Bishop
    username: localadmin
    hostname: ubuntu-desktop-test
  kernel:
    package: linux-generic-hwe-24.04
  keyboard:
    layout: gb
    toggle: null
    variant: ''
  locale: en_GB.UTF-8
  oem:
    install: auto
  source:
    id: ubuntu-desktop-minimal
    search_drivers: false
  ssh:
    allow-pw: false
    authorized-keys: []
    install-server: true
  timezone: Europe/London
  updates: security
